specVersion: 1.0.0
name: thorchain-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Thorchain) based SubQuery project
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: thorchain-mainnet-v1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: "https://rpc.ninerealms.com/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/cosmos-hub-dictionary"
  chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
    thorchain.message.observed.out: # Key is not used, it matches the one above and is inferred from the file
      file: ./proto/thorchain/v1/x/thorchain/types/msg_observed_txout.proto
      messages:
        - MsgObservedTxOut
    thorchain.message.deposit: # Key is not used, it matches the one above and is inferred from the file
      file: ./proto/thorchain/v1/x/thorchain/types/msg_deposit.proto
      messages:
        - MsgDeposit
    thorchain.types.observed.out: # Key is not used, it matches the one above and is inferred from the file
      file: ./proto/thorchain/v1/x/thorchain/types/type_observed_tx.proto
      messages:
        - ObservedTx
    common.Common: # Key is not used, it matches the one above and is inferred from the file
      file: ./proto/thorchain/v1/common/common.proto
      messages:
        - Tx
dataSources:
  - kind: cosmos/Runtime
    startBlock: 7960001 # This is the lowest height on the current version of Thorchain
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every block
        # - handler: handleTransaction
        # - handler: handleEvent
        #   kind: cosmos/EventHandler
        #   filter:
        #     type: swap
        #     messageFilter:
        #       type: swap
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /types.MsgDeposit
