specVersion: 1.0.0

name: okx-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your Cosmos (Cronos) based SubQuery project via the Etheruem API"
repository: "https://github.com/subquery/cosmos-subql-starter/tree/main/Cronos/cronos-evm-starter-via-eth"
schema:
  file: ./schema.graphql
network:
  chainId: "66"
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # Take a look here for some Cronos endpoints https://moonflow.solutions/rpc-servers
  endpoint: "https://exchainrpc.okex.org/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/cosmos-okx-dictionary"
dataSources:
  - kind: ethereum/Runtime
    startBlock: 2348876 # Block that this contract was created
    options:
      abi: erc20
      address: "0x382bb369d343125bfb2117af9c149795c6c65c50" # USDT https://www.oklink.com/en/okc/address/0x382bb369d343125bfb2117af9c149795c6c65c50
    assets:
      erc20:
        file: "erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: ethereum/BlockHandler
        - handler: handleTransaction
          kind: ethereum/TransactionHandler
          filter:
            ## The function can either be the function fragment or signature
            ## https://docs.ethers.io/v5/api/utils/abi/fragments/#FunctionFragment
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: approve(address spender, uint256 value)
        - handler: handleLog
          kind: ethereum/LogHandler
          filter:
            topics:
              # The topics filter follows the Ethereum JSON-PRC log filters
              # https://docs.ethers.io/v5/concepts/events
              # Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              - Transfer(address from, address to, uint256 value)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
