--
-- Restore pg_type enum and dependency records
--
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16400, 'app_enum_15c287bea7', 2200, 10, 4, true, 'e', 'E', false, true, ',', 0, '-', 0, 16399, 'enum_in', 'enum_out', 'enum_recv', 'enum_send', '-', '-', '-', 'i', 'p', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16399, '_app_enum_15c287bea7', 2200, 10, -1, false, 'b', 'A', false, true, ',', 0, 'array_subscript_handler', 16400, 0, 'array_in', 'array_out', 'array_recv', 'array_send', '-', '-', 'array_typanalyze', 'i', 'x', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16412, 'app_enum_1c563c52f4', 2200, 10, 4, true, 'e', 'E', false, true, ',', 0, '-', 0, 16411, 'enum_in', 'enum_out', 'enum_recv', 'enum_send', '-', '-', '-', 'i', 'p', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16411, '_app_enum_1c563c52f4', 2200, 10, -1, false, 'b', 'A', false, true, ',', 0, 'array_subscript_handler', 16412, 0, 'array_in', 'array_out', 'array_recv', 'array_send', '-', '-', 'array_typanalyze', 'i', 'x', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16418, 'app_enum_0f6c2478ba', 2200, 10, 4, true, 'e', 'E', false, true, ',', 0, '-', 0, 16417, 'enum_in', 'enum_out', 'enum_recv', 'enum_send', '-', '-', '-', 'i', 'p', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16417, '_app_enum_0f6c2478ba', 2200, 10, -1, false, 'b', 'A', false, true, ',', 0, 'array_subscript_handler', 16418, 0, 'array_in', 'array_out', 'array_recv', 'array_send', '-', '-', 'array_typanalyze', 'i', 'x', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16426, 'app_enum_c55bdb5a48', 2200, 10, 4, true, 'e', 'E', false, true, ',', 0, '-', 0, 16425, 'enum_in', 'enum_out', 'enum_recv', 'enum_send', '-', '-', '-', 'i', 'p', false, 0, -1, 0, 0, null, null, null);
INSERT INTO pg_catalog.pg_type (oid, typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typsubscript, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl) VALUES (16425, '_app_enum_c55bdb5a48', 2200, 10, -1, false, 'b', 'A', false, true, ',', 0, 'array_subscript_handler', 16426, 0, 'array_in', 'array_out', 'array_recv', 'array_send', '-', '-', 'array_typanalyze', 'i', 'x', false, 0, -1, 0, 0, null, null, null);

--
-- Restore pg_enum records
--
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16402, 16400, 1, 'EMPTY');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16404, 16400, 2, 'YES');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16406, 16400, 3, 'ABSTAIN');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16408, 16400, 4, 'NO');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16410, 16400, 5, 'NO_WITH_VETO');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16414, 16412, 1, 'Success');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16416, 16412, 2, 'Error');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16420, 16418, 1, 'Uncertain');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16422, 16418, 2, 'CW20');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16424, 16418, 3, 'LegacyBridgeSwap');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16428, 16426, 1, 'Unspecified');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16430, 16426, 2, 'AccessTypeNobody');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16432, 16426, 3, 'AccessTypeOnlyAddress');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16434, 16426, 4, 'AccessTypeEverybody');
INSERT INTO pg_catalog.pg_enum (oid, enumtypid, enumsortorder, enumlabel) VALUES (16436, 16426, 5, 'AccessTypeAnyOfAddresses');
