specVersion: 1.0.0
name: osmosis-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos
  (Osmosis) based SubQuery project. This Cosmos Example Project indexes all swaps on Osmosis' on chain DEX
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: osmosis-1
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime.
  # This is a public node that is rate limited, which will affect indexing speed.
  # When developing your project we strongly suggest getting a private API key.
  endpoint: ["https://osmosis.api.onfinality.io/public"]
  dictionary: "https://api.subquery.network/sq/subquery/cosmos-osmosis-dictionary"
  chaintypes:
    osmosis.gamm.v1beta1:
      file: "./proto/osmosis/gamm/v1beta1/tx.proto"
      messages:
        - MsgSwapExactAmountIn
    osmosis.poolmanager.v1beta1: # needed by MsgSwapExactAmountIn
      file: "./proto/osmosis/poolmanager/v1beta1/swap_route.proto"
      messages:
        - SwapAmountInRoute
    cosmos.base.v1beta1: # needed by MsgSwapExactAmountIn
      file: "./proto/cosmos/base/v1beta1/coin.proto"
      messages:
        - "Coin"
dataSources:
  - kind: cosmos/Runtime
    startBlock: 9798050
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every transaction
        # - handler: handleTransaction
        #   kind: cosmos/TransactionHandler
        # - handler: handleEvent
        #  kind: cosmos/EventHandler
        #  filter:
        #    type: token_swapped
        #    messageFilter:
        #      type: /osmosis.gamm.v1beta1.MsgSwapExactAmountIn
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /osmosis.gamm.v1beta1.MsgSwapExactAmountIn
