specVersion: 1.0.0
name: injective-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Injective) based SubQuery project
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: injective-1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: "http://archival-sentry-equinix-2.injective.dev:26657"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/injective-hub-dictionary"
  chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
    injective.exchange.v1beta1.MsgCreateSpotLimitOrder: # Key is not used, it matches the one above and is inferred from the file
      file: ./proto/injective/exchange/v1beta1/tx.proto
      messages:
        - MsgCreateSpotLimitOrder
    injective.exchange.v1beta1.SpotOrder:
      file: ./proto/injective/exchange/v1beta1/exchange.proto
      messages:
        - SpotOrder
dataSources:
  - kind: cosmos/Runtime
    startBlock: 22186475
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every block
        # - handler: handleTransaction
        # - handler: handleEvent
        #   kind: cosmos/EventHandler
        #   filter:
        #     type: transfer
        #     messageFilter:
        #       type: /injective.exchange.v1beta1.MsgCreateSpotLimitOrder
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /injective.exchange.v1beta1.MsgCreateSpotLimitOrder
