specVersion: 1.0.0
name: archway-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Archway) based SubQuery project
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: archway-1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: [
      "https://rpc.mainnet.archway.io:443",
      #"https://rpc-archway.cosmos-spaces.cloud",
      #"https://rpc-1.archway.nodes.guru",
    ]
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/cosmos-archway-dictionary"
  chainTypes: # This feature allows support for any Cosmos chain by importing the correct protobuf messages
    cosmwasm.wasm.v1.MsgSetContractMetadata:
      file: ./proto/archway/rewards/v1/tx.proto
      messages:
        - MsgSetContractMetadata
    cosmwasm.wasm.v1.ContractMetadata:
      file: ./proto/archway/rewards/v1/rewards.proto
      messages:
        - ContractMetadata
dataSources:
  - kind: cosmos/Runtime
    startBlock: 1338 # The first contract metadata was instantiated on this block
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every block
        # - handler: handleTransaction
        #   kind: cosmos/TransactionHandler
        - handler: handleRewardsWithdrawEvent
          kind: cosmos/EventHandler
          filter:
            type: "archway.rewards.v1.RewardsWithdrawEvent"
            messageFilter:
              type: "/archway.rewards.v1.MsgWithdrawRewards"
        # contractCall field can be specified here too
        # values: # A set of key/value pairs that are present in the message data
        # contract: "juno1v99ehkuetkpf0yxdry8ce92yeqaeaa7lyxr2aagkesrw67wcsn8qxpxay0"
        - handler: handleSetContractMetadata
          kind: cosmos/MessageHandler
          filter:
            # Filter to only messages with the MsgSetContractMetadata function call
            # e.g. https://archway.explorers.guru/transaction/EBEE24728FCDA79EF167625D66F438236ED17579CAA7229A562C5AB84608B5A4
            type: "/archway.rewards.v1.MsgSetContractMetadata"
