specVersion: 1.0.0
name: okex-starter-via-rpc
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your Cosmos (OKX Exchain) based SubQuery project via the Ethermint RPC API"
repository: "https://github.com/subquery/cosmos-subql-starter/tree/main/OKX/okx-starter-via-rpc"
schema:
  file: ./schema.graphql
network:
  chainId: exchain-66
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # Take a look here for some Cronos endpoints https://moonflow.solutions/rpc-servers
  endpoint: "https://exchaintmrpc.okex.org/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/cosmos-okx-dictionary"
  chainTypes:
    ethermint.evm.v1:
      file: "./proto/ethermint/evm/v1/tx.proto"
      messages:
        - "MsgEthereumTx"
        - "LegacyTx"
        - "AccessListTx"
        - "DynamicFeeTx"
    ethermint.evm.v12:
      file: "./proto/ethermint/evm/v1/evm.proto"
      messages:
        - "AccessTuple"
    google.protobuf:
      file: "./proto/google/protobuf/any.proto"
      messages:
        - "Any"

dataSources:
  - kind: cosmos/EthermintEvm
    startBlock: 15643080 # Block that this contract was created
    processor:
      file: "./node_modules/@subql/ethermint-evm-processor/dist/bundle.js"
      options:
        abi: erc20
        address: "0x382bb369d343125bfb2117af9c149795c6c65c50" # USDT
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        - handler: handleEthermintEvmCall
          kind: cosmos/EthermintEvmCall
          filter:
            # Either Function Signature strings or the function `sighash` to filter the function called on the contract
            # ](https://docs.ethers.io/v5/api/utils/abi/fragments/#FunctionFragment)
            method: (address _spender, uint256 _value)
        - handler: handleEthermintEvmEvent
          kind: cosmos/EthermintEvmEvent
          filter:
            topics:
              # The topics filter follows the Ethereum JSON-PRC log filters
              # https://docs.ethers.io/v5/concepts/events
              # Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              - Transfer(address from, address to, uint256 value)
