specVersion: 1.0.0
name: fetchhub-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-cosmos'
    version: '>=0.1.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Cosmos
  (Fetch.ai) based SubQuery project
repository: 'https://github.com/subquery/juno-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: fetchhub-4
  #  This endpoint might not be publicly available
  endpoint: 'https://rpc-fetchhub.fetch.ai'
  dictionary: 'https://api.subquery.network/sq/subquery/cosmos-fetch-ai-dictionary'
  chainTypes:
    cosmos.slashing.v1beta1:
      file: ./proto/cosmos/slashing/v1beta1/tx.proto
      messages:
        - MsgUnjail
    cosmos.gov.v1beta1:
      file: ./proto/cosmos/gov/v1beta1/tx.proto
      messages:
        - MsgVoteWeighted
    cosmos.gov.v1beta1.gov:
      file: ./proto/cosmos/gov/v1beta1/gov.proto
      messages:
        - WeightedVoteOption
dataSources:
  - kind: cosmos/Runtime
    startBlock: 5300201
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: transfer
            messageFilter:
              type: /cosmos.bank.v1beta1.MsgSend
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /cosmos.bank.v1beta1.MsgSend
