specVersion: 1.0.0
name: axelar-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Axelar) based SubQuery project
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: axelar-dojo-1
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: ["https://axelar-archrpc.chainode.tech/"]
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/axelar-hub-dictionary"
dataSources:
  - kind: cosmos/Runtime
    startBlock: 5262 # The first deposit event occurs on this block
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every block
        # - handler: handleTransaction
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: "depositConfirmation"
        # - handler: handleMessage
        #   kind: cosmos/MessageHandler
        #   filter:
        #     type: /cosmos.bank.v1beta1.MsgSend
